version: '3'

services:
  gameframe-gateway:
    build: .
    container_name: gameframe-userservice
    ports:
      - "8090:8090"
    expose:
      - "8090/tcp"
    networks:
      - gameframe-internal-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  gameframe-internal-network:
    external: true
